receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4327
      http:
#  jaeger:
#    protocols:
#      grpc:
#      thrift_binary:
#      thrift_compact:
#      thrift_http:

exporters:
  otlp:
    endpoint: localhost:50051
    insecure: true
  jaeger:
#   endpoint: localhost:50061
    endpoint: localhost:14250
    insecure: true
  logging:
    loglevel: debug

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, jaeger, logging]
      processors: [batch]
