apiVersion: v1
kind: Service
metadata:
  name: sws-example-java-petclinic
spec:
  type: LoadBalancer
  selector:
    app: sws-example-java-petclinic
  ports:
    - name: http
      port: 9966
      targetPort: 9966
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sws-example-java-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sws-example-java-petclinic
  template:
    metadata:
      labels:
        app: sws-example-java-petclinic
    spec:
      containers:
        - name: sws-example-java-petclinic
          image: sws-example-java-petclinic
          ports:
          - containerPort: 9966
          env:
          - name: PORT
            value: "9966"
          readinessProbe:
            tcpSocket:
              port: 9966
            initialDelaySeconds: 5


