apiVersion: v1
kind: Service
metadata:
  name: sws-example-express
spec:
  type: LoadBalancer
  selector:
    app: sws-example-express
  ports:
    - name: http
      port: 3040
      targetPort: 3040
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sws-example-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sws-example-express
  template:
    metadata:
      labels:
        app: sws-example-express
    spec:
      containers:
        - name: sws-example-express
          image: sws-example-express
          ports:
          - containerPort: 3040
          env:
          - name: PORT
            value: "3040"
          readinessProbe:
            tcpSocket:
              port: 3040
            initialDelaySeconds: 5


