version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.28.0
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yml:/conf/collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "9411"   # Zipkin receiver
      - "55680:55679" # zpages extension
    network_mode: host
