receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4327
#  jaeger:
#    protocols:
#      thrift_http:
#        endpoint: 0.0.0.0:14278
#      grpc:
#      thrift_binary:
#      thrift_compact:

exporters:
  # swagger-stats otlp grpc receiver
  otlp:
    endpoint: localhost:50051
    insecure: true
  otlp/2:
    endpoint: localhost:55680
    insecure: true
  # tempo Jaeger Grpc receiver
  jaeger:
    #endpoint: localhost:50061
    endpoint: localhost:14268
    insecure: true
  logging:
    loglevel: debug

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, otlp/2, logging]
      processors: [batch]
