version: '3'
services:
  redis:
    build: .
    ports:
      - 6379:6379
    volumes:
      - /mnt/data/redis:/data
    network_mode: host
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - /mnt/data/redisinsight:/db
    network_mode: host
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
