global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'tempo'
    static_configs:
    - targets: ['localhost:3150']
  - job_name: 'otelcol'
    static_configs:
      - targets: ['localhost:8888']
  - job_name: 'loki'
    static_configs:
      - targets: ['localhost:3100']
  - job_name: 'sws'
    static_configs:
      - targets: [ 'localhost:3060' ]